# Generated by Django 5.1.2 on 2024-11-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
