# Generated by Django 5.1.2 on 2024-11-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_cart_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at']},
        ),
    ]
