# Generated by Django 5.1.2 on 2024-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_colorvariant_price_remove_sizevariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
