# Generated by Django 5.1.2 on 2024-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category_delete_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorvariant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
