# Generated by Django 5.1.2 on 2024-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
